Stripper:
- any:
  - changed-files:
    - any-glob-to-any-file: 'stripper/**'

Map Config:
- any:
  - changed-files:
    - any-glob-to-any-file: 'mapcfg/*'

EntWatch:
- any:
  - changed-files:
    - any-glob-to-any-file: 'entwatch/*'

MusicName:
- any:
  - changed-files:
    - any-glob-to-any-file: 'musicname/*'

AdminRoom:
- any:
  - changed-files:
    - any-glob-to-any-file: 'adminroom/*'

BossHUD:
- any:
  - changed-files:
    - any-glob-to-any-file: 'bosshud/*'