Stripper:
- any:
  - changed-files:
    - any-glob-to-any-file: 'stripper/**'

Map Config:
- any:
  - changed-files:
    - any-glob-to-any-file: 'mapcfg/*'

EntWatch:
- any:
  - changed-files:
    - any-glob-to-any-file: 'entwatch/*'